### ISSUE TITLE
make reading from standard input platform-independent

### ISSUE THREAD

**Issue by christf** [christf/SnuselPi#3]
/dev/stdin gibt es nur unter *nix

**Comment by penguineer** [comment]
Siehe auch: 7f134b498c5e8bcdc9cc1885500c6569f83b1a91

Könnte man mit dem VFS überein bringen, indem ein generischer iterator über alle relevanten quellen definiert wird - der kann dann /dev/stdin zurückliefern (und dafür VFS nicht nutzen), was sich dann zu System.in auflösen lässt. oder der liefert direkt Streams. Ich denk da morgen mal drüber nach.
